### ISSUE TITLE
Missing Context in Quoted Post Embeds with bskye

### ISSUE THREAD

**Issue by SalbugVR** [FerroEduardo/bskye#1]
Currently, when you embed a quoted post using `bskye`, the embed omits the original context of the post, displaying only the user who quoted it. I believe it is important to include the original context, as shown in the image below.

![image](https://github.com/user-attachments/assets/576a61da-1f96-4ff6-b0a7-ce9ebcd0829b)

**Comment by FerroEduardo** [comment]
It should be working now (the mentioned post may be cached and not will show properly)

**Comment by FerroEduardo** [comment]
Thanks for the feedback :)

**Comment by SalbugVR** [comment]
You're welcome and thank you! ^^
